/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReadIGES */

#ifndef _Included_ReadIGES
#define _Included_ReadIGES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ReadIGES
 * Method:    readFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ReadIGES_readFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
